# Generated by Django 5.0.1 on 2024-02-02 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_url', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('personal_information', models.JSONField()),
                ('profile', models.JSONField()),
                ('experience', models.JSONField()),
                ('skills', models.JSONField()),
                ('hide_text', models.TextField()),
            ],
        ),
    ]
