# Generated by Django 5.0.3 on 2024-03-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_api', '0002_resume_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user_id',
            new_name='user',
        ),
    ]
