# Generated by Django 5.0.3 on 2024-04-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('isOptional', models.BooleanField(blank=True, default=False, null=True)),
                ('inputType', models.CharField(default='text', max_length=255)),
                ('answer', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_management.profile')),
            ],
        ),
    ]
