# Generated by Django 5.0.3 on 2024-07-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardquestion',
            name='standard_question',
            field=models.TextField(),
        ),
    ]
