# Generated by Django 5.0.7 on 2024-07-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bid', '0002_alter_standardquestion_standard_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
