# Generated by Django 5.0.3 on 2024-04-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobpost_banner_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='interval',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('hourly', 'Hourly')], default='yearly', max_length=20, null=True),
        ),
    ]
