# Generated by Django 5.0.3 on 2024-04-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_jobpost_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='interval',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('hourly', 'Hourly')], max_length=20, null=True),
        ),
    ]
