# Generated by Django 5.0.3 on 2024-04-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_jobpost_company_url_alter_jobpost_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_url_direct',
            field=models.TextField(blank=True, null=True),
        ),
    ]
