# Generated by Django 5.0.3 on 2024-04-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_jobpost_currency_alter_jobpost_job_url_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_easy_apply',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='is_remote',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
