# Generated by Django 5.0.3 on 2024-04-12 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobpost_is_easy_apply_alter_jobpost_is_remote'),
        ('profile_management', '0002_alter_experience_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='job.jobpost')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profile_management.profile')),
            ],
            options={
                'unique_together': {('job', 'profile')},
            },
        ),
    ]
