# Generated by Django 5.0.3 on 2024-03-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='user',
        ),
    ]
